import {
  type RouteAnalyticsSummaryResponse,
  validateRouteAnalyticsSummaryResponse,
} from "contracts";
import { PROVIDER_NAME, PROVIDER_PAY_TO, PROTAGONIST_ADDRESS, T0 } from "./shared";
import { syntheticAddress } from "./wallets";

const GENERATED_AT = new Date(T0 * 1000).toISOString();

const fixtureSummary = (): RouteAnalyticsSummaryResponse =>
  validateRouteAnalyticsSummaryResponse({
    generatedAt: GENERATED_AT,
    generatedFrom: "frontend-fixture-route-analytics",
    routeCount: 6,
    workflowCount: 4,
    paidWorkflowCount: 4,
    settledUsd: 8127.43,
    successRate: 0.94,
    repeatUsage: 18,
    paymentToAccessConversion: 0.88,
    rails: [
      {
        rail: "x402",
        routeCount: 3,
        workflowCount: 2,
        paidWorkflowCount: 2,
        settledUsd: 4210.12,
        successRate: 0.93,
        repeatUsage: 9,
        visibility: "demo_label",
      },
      {
        rail: "stripe_mpp",
        routeCount: 2,
        workflowCount: 1,
        paidWorkflowCount: 1,
        settledUsd: 2610.2,
        successRate: 0.97,
        repeatUsage: 6,
        visibility: "demo_label",
      },
      {
        rail: "hitpay_mpp",
        routeCount: 1,
        workflowCount: 1,
        paidWorkflowCount: 1,
        settledUsd: 1307.11,
        successRate: 0.91,
        repeatUsage: 3,
        visibility: "demo_label",
      },
    ],
    sampleRoutes: [
      {
        routeId: "route:x402:northwind-price",
        workflowId: "workflow:price",
        rail: "x402",
        protocol: "x402",
        sourceRoute: "Direct API client",
        sourcePlatform: "direct",
        router: "Base",
        providerId: "northwind-price",
        endpointGroup: PROVIDER_NAME["northwind-price"],
        payerIdentity: PROTAGONIST_ADDRESS,
        payeeIdentity: PROVIDER_PAY_TO["northwind-price"],
        amountUsd: 1840.5,
        currency: "USD",
        status: "settled",
        settlementRef: { type: "onchain_tx", value: "demo_x402_northwind" },
        visibility: "demo_label",
        provenance: "demo_label",
        provenanceByField: { rail: "demo_label", router: "demo_label" },
        timestamp: GENERATED_AT,
        latencyMs: 180,
        reasons: [{ provenance: "demo_label", label: "frontend fixture route" }],
      },
      {
        routeId: "route:stripe-mpp:vectormind",
        workflowId: "workflow:inference",
        rail: "stripe_mpp",
        protocol: "mpp",
        sourceRoute: "MCP directory",
        sourcePlatform: "mcp-directory",
        router: "Tempo",
        providerId: "vectormind",
        endpointGroup: PROVIDER_NAME.vectormind,
        payerIdentity: syntheticAddress("sdk:secondary:claude", "evm"),
        payeeIdentity: PROVIDER_PAY_TO.vectormind,
        amountUsd: 2610.2,
        currency: "USD",
        status: "settled",
        settlementRef: { type: "stripe_payment_intent", value: "pi_demo_fixture" },
        visibility: "demo_label",
        provenance: "demo_label",
        provenanceByField: { rail: "demo_label", router: "demo_label" },
        timestamp: GENERATED_AT,
        latencyMs: 240,
        reasons: [{ provenance: "demo_label", label: "frontend fixture route" }],
      },
      {
        routeId: "route:hitpay-mpp:signalport",
        workflowId: "workflow:notify",
        rail: "hitpay_mpp",
        protocol: "mpp",
        sourceRoute: "pay.sh",
        sourcePlatform: "pay.sh",
        router: "Solana",
        providerId: "signalport",
        endpointGroup: PROVIDER_NAME.signalport,
        payerIdentity: syntheticAddress("sdk:secondary:n8n", "solana"),
        payeeIdentity: PROVIDER_PAY_TO.signalport,
        amountUsd: 1307.11,
        currency: "USD",
        status: "settled",
        settlementRef: { type: "hitpay_charge", value: "hp_demo_fixture" },
        visibility: "demo_label",
        provenance: "demo_label",
        provenanceByField: { rail: "demo_label", router: "demo_label" },
        timestamp: GENERATED_AT,
        latencyMs: 210,
        reasons: [{ provenance: "demo_label", label: "frontend fixture route" }],
      },
      {
        routeId: "route:x402:routezero",
        workflowId: "workflow:swap",
        rail: "x402",
        protocol: "x402",
        sourceRoute: "Direct",
        sourcePlatform: "direct",
        router: "Base",
        providerId: "routezero",
        endpointGroup: PROVIDER_NAME.routezero,
        payerIdentity: syntheticAddress("sdk:secondary:cursor", "evm"),
        payeeIdentity: PROVIDER_PAY_TO.routezero,
        amountUsd: 980.4,
        currency: "USD",
        status: "settled",
        settlementRef: { type: "onchain_tx", value: "demo_x402_routezero" },
        visibility: "demo_label",
        provenance: "demo_label",
        provenanceByField: { rail: "demo_label", router: "demo_label" },
        timestamp: GENERATED_AT,
        latencyMs: 160,
        reasons: [{ provenance: "demo_label", label: "frontend fixture route" }],
      },
    ],
    provenance: "demo_label",
    provenanceByField: { rails: "demo_label" },
    reasons: [{ provenance: "demo_label", label: "frontend fixture route analytics" }],
  });

export function getFixtureRouteAnalyticsSummary(): RouteAnalyticsSummaryResponse {
  return fixtureSummary();
}
