import { chainKindFromNetwork, syntheticAddress } from "@/lib/sdk-fixtures/wallets";

export type StaticProviderCapability = {
  serviceId: string;
  name: string;
  networks: string[];
  protocols: ("x402" | "MPP")[];
  payTo: string;
  network: string;
  asset: string;
  catalogSource: "base_curated" | "pay_sh_curated";
  transactionCount: number;
  uniqueSenderCount: number;
};

// Minimal frontend catalog of public provider names and capabilities.
// payTo values are deterministic synthetic addresses so the public mock
// never ships wallet-level on-chain identities.
const rows = [
  [
    "agentmail/email",
    "AgentMail",
    ["avalanche", "base", "solana", "x-layer"],
    ["x402"],
    "-",
    "x-layer",
    "ERC20:0x74b7f16337b8972027f6196a17a631ac6de26d22",
    "pay_sh_curated",
    145,
    34,
  ],
  [
    "api.nansen.ai",
    "Nansen",
    ["base", "solana", "x-layer"],
    ["x402"],
    "-",
    "base",
    "USDC",
    "base_curated",
    147,
    7,
  ],
  [
    "crushrewards/pricing",
    "Crush Rewards",
    ["base", "solana", "tempo"],
    ["x402", "MPP"],
    "-",
    "tempo",
    "USD (Tempo)",
    "pay_sh_curated",
    146,
    27,
  ],
  [
    "dtelecom/voice",
    "dTelecom",
    ["base", "solana"],
    ["x402"],
    "-",
    "solana",
    "USDC",
    "pay_sh_curated",
    82,
    16,
  ],
  [
    "merit-systems/stablecrypto/market-data",
    "StableCrypto",
    ["base", "solana", "tempo"],
    ["x402", "MPP"],
    "-",
    "tempo",
    "USD (Tempo)",
    "pay_sh_curated",
    130,
    26,
  ],
  [
    "merit-systems/stableemail/email",
    "StableEmail",
    ["base", "solana", "tempo"],
    ["x402", "MPP"],
    "-",
    "tempo",
    "USD (Tempo)",
    "pay_sh_curated",
    135,
    27,
  ],
  [
    "merit-systems/stableenrich/enrichment",
    "StableEnrich",
    ["base", "solana", "tempo"],
    ["x402", "MPP"],
    "-",
    "tempo",
    "USD (Tempo)",
    "pay_sh_curated",
    78,
    17,
  ],
  [
    "merit-systems/stablephone/calls",
    "StablePhone",
    ["base", "solana", "tempo"],
    ["x402", "MPP"],
    "-",
    "tempo",
    "USD (Tempo)",
    "pay_sh_curated",
    116,
    25,
  ],
  [
    "merit-systems/stablesocial/social-data",
    "StableSocial",
    ["base", "solana", "tempo"],
    ["x402", "MPP"],
    "-",
    "tempo",
    "USD (Tempo)",
    "pay_sh_curated",
    112,
    25,
  ],
  [
    "paysponge/perplexity",
    "Perplexity AI API",
    ["base", "solana"],
    ["x402"],
    "-",
    "solana",
    "USDC",
    "pay_sh_curated",
    93,
    16,
  ],
  [
    "paysponge/rentcast",
    "RentCast API",
    ["base", "solana"],
    ["x402"],
    "-",
    "solana",
    "USDC",
    "pay_sh_curated",
    98,
    18,
  ],
  [
    "pro-api.coingecko.com",
    "pro-api.coingecko.com",
    ["base", "solana"],
    ["x402"],
    "-",
    "base",
    "USDC",
    "base_curated",
    1935,
    150,
  ],
  [
    "purch/marketplace",
    "Purch",
    ["solana"],
    ["x402"],
    "-",
    "solana",
    "USDC",
    "pay_sh_curated",
    30,
    7,
  ],
  [
    "quicknode/rpc",
    "QuickNode",
    [
      "base",
      "base-sepolia",
      "eip155:1952 (unknown)",
      "eip155:5042002 (unknown)",
      "polygon",
      "polygon-amoy",
      "solana",
      "x-layer",
    ],
    ["x402"],
    "-",
    "solana",
    "USDC",
    "pay_sh_curated",
    463,
    92,
  ],
  [
    "solana-foundation/alibaba/agentexplorer",
    "Alibaba Cloud Agent Skills Explorer",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    120,
    28,
  ],
  [
    "solana-foundation/alibaba/aigen",
    "Alibaba Cloud AI Generation",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    122,
    26,
  ],
  [
    "solana-foundation/alibaba/anytrans",
    "Alibaba Cloud AnyTrans",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    117,
    23,
  ],
  [
    "solana-foundation/alibaba/captcha",
    "Alibaba Cloud CAPTCHA",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    121,
    26,
  ],
  [
    "solana-foundation/alibaba/cloudauth",
    "Alibaba Cloud Cloudauth",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    112,
    26,
  ],
  [
    "solana-foundation/alibaba/cloudauth-intl",
    "Alibaba Cloud Cloudauth International",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    159,
    32,
  ],
  [
    "solana-foundation/alibaba/contactcenterai",
    "Alibaba Cloud Contact Center AI",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    112,
    23,
  ],
  [
    "solana-foundation/alibaba/documentparseservice",
    "Alibaba Cloud Document Parse Service",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    55,
    14,
  ],
  [
    "solana-foundation/alibaba/edututor",
    "Alibaba Cloud EduTutor",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    115,
    34,
  ],
  [
    "solana-foundation/alibaba/embeddings",
    "Alibaba Cloud Model Studio Embeddings",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    118,
    25,
  ],
  [
    "solana-foundation/alibaba/facebody",
    "Alibaba Cloud Facebody",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    50,
    9,
  ],
  [
    "solana-foundation/alibaba/farui",
    "Alibaba Cloud FaRui",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    78,
    18,
  ],
  [
    "solana-foundation/alibaba/goodstech",
    "Alibaba Cloud Goods Tech",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    134,
    28,
  ],
  [
    "solana-foundation/alibaba/green",
    "Alibaba Cloud Green",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    160,
    34,
  ],
  [
    "solana-foundation/alibaba/imageaudit",
    "Alibaba Cloud Image Audit",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    142,
    31,
  ],
  [
    "solana-foundation/alibaba/imagerecog",
    "Alibaba Cloud Image Recognition",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    152,
    35,
  ],
  [
    "solana-foundation/alibaba/imageseg",
    "Alibaba Cloud Image Segmentation",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    96,
    19,
  ],
  [
    "solana-foundation/alibaba/intelligentspeechinteraction",
    "Alibaba Cloud Intelligent Speech Interaction",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    164,
    38,
  ],
  [
    "solana-foundation/alibaba/iqs",
    "Alibaba Cloud Information Query Service",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    86,
    23,
  ],
  [
    "solana-foundation/alibaba/ivpd",
    "Alibaba Cloud IVPD",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    128,
    25,
  ],
  [
    "solana-foundation/alibaba/machinetranslation",
    "Alibaba Cloud Machine Translation",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    143,
    30,
  ],
  [
    "solana-foundation/alibaba/objectdet",
    "Alibaba Cloud Object Detection",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    122,
    31,
  ],
  [
    "solana-foundation/alibaba/ocr",
    "Alibaba Cloud Model Studio OCR",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    79,
    19,
  ],
  [
    "solana-foundation/alibaba/ocr-api",
    "Alibaba Cloud OCR API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    99,
    21,
  ],
  [
    "solana-foundation/alibaba/paimodelgallery",
    "Alibaba Cloud PAI Model Gallery",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    99,
    22,
  ],
  [
    "solana-foundation/alibaba/rai",
    "Alibaba Cloud Responsible AI",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    193,
    43,
  ],
  [
    "solana-foundation/alibaba/saf",
    "Alibaba Cloud SAF",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    88,
    23,
  ],
  [
    "solana-foundation/alibaba/speech",
    "Alibaba Cloud Model Studio Speech Recognition",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    118,
    27,
  ],
  [
    "solana-foundation/alibaba/translate",
    "Alibaba Cloud Model Studio Translation",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    113,
    24,
  ],
  [
    "solana-foundation/alibaba/viapi-ocr",
    "Alibaba Cloud OCR (VIAPI)",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    126,
    31,
  ],
  [
    "solana-foundation/alibaba/videoenhan",
    "Alibaba Cloud Video Enhancement",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    153,
    31,
  ],
  [
    "solana-foundation/alibaba/videorecog",
    "Alibaba Cloud Video Recognition",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    111,
    29,
  ],
  [
    "solana-foundation/alibaba/videoseg",
    "Alibaba Cloud Video Segmentation",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    106,
    24,
  ],
  [
    "solana-foundation/google/addressvalidation",
    "Address Validation API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    83,
    23,
  ],
  [
    "solana-foundation/google/airquality",
    "Air Quality API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    146,
    26,
  ],
  [
    "solana-foundation/google/language",
    "Cloud Natural Language API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    65,
    10,
  ],
  [
    "solana-foundation/google/places",
    "Places API (New)",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    111,
    26,
  ],
  [
    "solana-foundation/google/speech",
    "Cloud Speech-to-Text API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    80,
    17,
  ],
  [
    "solana-foundation/google/texttospeech",
    "Cloud Text-to-Speech API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    153,
    29,
  ],
  [
    "solana-foundation/google/videointelligence",
    "Cloud Video Intelligence API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    94,
    19,
  ],
  [
    "solana-foundation/google/vision",
    "Cloud Vision API",
    ["solana"],
    ["MPP"],
    "-",
    "solana",
    "CASH",
    "pay_sh_curated",
    117,
    27,
  ],
] as const;

export const STATIC_PROVIDER_CAPABILITIES = rows.map(
  ([
    serviceId,
    name,
    networks,
    protocols,
    _payTo,
    network,
    asset,
    catalogSource,
    transactionCount,
    uniqueSenderCount,
  ]) => ({
    serviceId,
    name,
    networks: [...networks],
    protocols: [...protocols],
    payTo: syntheticAddress(`catalog:${serviceId}`, chainKindFromNetwork(network)),
    network,
    asset,
    catalogSource,
    transactionCount,
    uniqueSenderCount,
  }),
) satisfies StaticProviderCapability[];

export const STATIC_PROVIDER_CAPABILITY_BY_SERVICE_ID: ReadonlyMap<
  string,
  StaticProviderCapability
> = new Map(
  STATIC_PROVIDER_CAPABILITIES.map((provider) => [provider.serviceId, provider] as const),
);
